const data = [
    "Naruto",
    "One Piece",
    "Attack on Titan",
    "Demon Slayer",
    "Jujutsu Kaisen",
    "My Hero Academia",
    "Fullmetal Alchemist: Brotherhood",
    "Death Note",
    "Dragon Ball Z",
    "Bleach",
    "Hunter x Hunter",
    "Sword Art Online",
    "One Punch Man",
    "Tokyo Revengers",
    "Black Clover",
    "Fairy Tail",
    "Re:Zero - Starting Life in Another World",
    "Dr. Stone",
    "The Rising of the Shield Hero",
    "Code Geass: Lelouch of the Rebellion",
    "Haikyuu!!",
    "Blue Lock",
    "Spy x Family",
    "Chainsaw Man",
    "Vinland Saga",
    "Mushoku Tensei: Jobless Reincarnation",
    "Akame ga Kill!",
    "Fire Force",
    "The Promised Neverland",
    "Noragami",
    "Your Lie in April",
    "Clannad",
    "Steins;Gate",
    "Erased",
    "Kaguya-sama: Love is War",
    "Horimiya",
    "Toradora!",
    "Made in Abyss",
    "The Seven Deadly Sins",
    "Overlord",
    "No Game No Life",
    "That Time I Got Reincarnated as a Slime",
    "Konosuba: God's Blessing on This Wonderful World!",
    "Assassination Classroom",
    "Sword of the Stranger",
    "Howl's Moving Castle",
    "Spirited Away",
    "Princess Mononoke",
    "Your Name",
    "Weathering with You",
    "A Silent Voice",
    "Ghost in the Shell",
    "Neon Genesis Evangelion",
    "Parasyte: The Maxim",
    "Berserk",
    "Gintama",
    "Fate/stay night: Unlimited Blade Works",
    "Fate/Zero",
    "Rurouni Kenshin",
    "Samurai Champloo",
    "Cowboy Bebop",
    "Trigun",
    "Yu Yu Hakusho",
    "Hellsing Ultimate",
    "Elfen Lied",
    "Black Lagoon",
    "Re:Creators",
    "Charlotte",
    "Angel Beats!",
    "Monster",
    "Great Teacher Onizuka (GTO)",
    "Baccano!",
    "Durarara!!",
    "The Melancholy of Haruhi Suzumiya",
    "Lucky Star",
    "Nichijou",
    "K-On!",
    "Barakamon",
    "Arakawa Under the Bridge",
    "Kimi ni Todoke",
    "Ao Haru Ride",
    "Fruits Basket",
    "Nana",
    "Beastars",
    "March Comes in Like a Lion",
    "Yona of the Dawn",
    "Zankyou no Terror (Terror in Resonance)",
    "Death Parade",
    "Ping Pong the Animation",
    "The Tatami Galaxy",
    "Devilman Crybaby",
    "Serial Experiments Lain",
    "Kaiji: Ultimate Survivor",
    "Welcome to the NHK",
    "Ergo Proxy"
  ];

  export default data;